export GOOGLE_APPLICATION_CREDENTIALS="maggie-and-ollie-wedding-abcc08241ee5.json"
# export GOOGLE_SERVICE_APPLICATION_CREDENTIALS="maggie-and-ollie-wedding-553536a7cfa6.json"
export TREEAPP_API_URL="api-test.thetreeapp.org"
export TREEAPP_API_KEY="b2b_test_sgS2KopWbNrAv2gOfsCVDpcIy8Um9Hxn8CuQHVcCuWHcFCjWwf5gfOVeO9NZ7zx5va5WdLckBkSYwZhsi2NuG9VQaEY0HNAv0E3"
export EMAIL_API_KEY="re_MEzUCBUK_LToyum42Q6dDx4PKVgCBwGEG"
export HEROKU_EMAIL_API_KEY="re_eLX3W2fY_3EGzf4P1E9h9EdvjRz8PU7ih"
python3 test.py
