export GOOGLE_APPLICATION_CREDENTIALS="maggie-and-ollie-wedding-f495c5daa1b5.json"
export GOOGLE_SERVICE_APPLICATION_CREDENTIALS="maggie-and-ollie-wedding-553536a7cfa6.json"
export TREEAPP_API_URL="api-test.thetreeapp.org"
export TREEAPP_API_KEY="b2b_test_sgS2KopWbNrAv2gOfsCVDpcIy8Um9Hxn8CuQHVcCuWHcFCjWwf5gfOVeO9NZ7zx5va5WdLckBkSYwZhsi2NuG9VQaEY0HNAv0E3"

python3 app.py